include: "/etc/unbound/unbound.conf.d/remote.conf"

server:
    verbosity: 1
    use-syslog: no
    log-servfail: yes

    interface: ::@53
    interface: 0.0.0.0@53

    do-tcp: yes
    do-udp: yes
    do-not-query-localhost: no
    prefer-ip6: yes
    tcp-upstream: yes
    so-reuseport: yes
    udp-upstream-without-downstream: yes
    verbosity: 2
    log-queries: yes
    log-replies: yes
    log-tag-queryreply: yes
    statistics-cumulative: yes
    extended-statistics: yes

    cache-min-ttl: 3600
    cache-max-negative-ttl: 3600
    cache-max-ttl: 86400
    prefetch: yes
    prefetch-key: yes
    minimal-responses: yes
    msg-cache-slabs: 2
    rrset-cache-slabs: 2
    infra-cache-slabs: 2
    key-cache-slabs: 2
    rrset-cache-size: 256m
    msg-cache-size: 128m

    tcp-idle-timeout: 300000
    outgoing-num-tcp: 32

    trust-anchor-file: /etc/unbound/root.key
    harden-glue: yes
    harden-dnssec-stripped: yes
    harden-referral-path: yes
    # use-caps-for-id: yes

    access-control: 0.0.0.0/0 refuse
    access-control: 127.0.0.0/8 allow
    access-control: ::0/0 refuse
    access-control: ::1 allow
    access-control: ::ffff:127.0.0.1 allow
    access-control: 192.168.43.0/24 allow
    access-control: fe80::/10 allow
    access-control: 10.1.0.0/24 allow
    access-control: fd00::/8 allow

    private-address: 10.0.0.0/8
    private-address: 172.16.0.0/12
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: fd00::/8
    private-address: fe80::/10
    private-address: ::ffff:0:0/96

    # Stub and Forward zones
    include: /etc/unbound/unbound.conf.d/zones.conf

    tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt

    include: "/etc/unbound/unbound.conf.d/forward.conf"
